updated cli install

diff --git a/usr/bin/install-opencart b/usr/bin/install-opencart
--- a/usr/bin/install-opencart
+++ b/usr/bin/install-opencart
@@ -372,10 +372,23 @@ else
     echo "create database IF NOT EXISTS $DATABASE" | mysql -u $MYSQL_USERNAME -p$MYSQL_PASS
 fi
 
-# todo fix error being generated from /install/cli_install.php
+
 if [ $? -eq 0 ]; then
     echo "Database $DATABASE Created Successfully."
     if [[ "$MYSQL_PASS" == '' ]]; then
+
+ # workaround for /install/cli_install.php since the authors refuse to make it sane.
+
+if [  -f /tmp/install/cli_install.php ];
+then
+   rm $DESTINATION_PATH/install/cli_install.php
+    rm $DESTINATION_PATH/install/opencart.sql
+    cp /tmp/install/cli_install.php $DESTINATION_PATH/install/.
+    cp /tmp/install/opencart.sql $DESTINATION_PATH/install/.
+  else
+  echo "Cannot find correct install script. install/cli_install.php not found. Manual install required."
+  exit $?
+fi
 
  #php $DESTINATION_PATH/install/cli_install.php install --db_driver $DBDRIVER --db_hostname $MYSQL_HOST  --db_username $MYSQL_USERNAME --db_password "" --db_database $DATABASE --db_prefix oc_ --username admin --password admin --email admin@example.com --agree_tnc yes --http_server $DOMAIN --domain $PROJECT_NAME 
  php $DESTINATION_PATH/install/cli_install.php install --db_driver $DBDRIVER --db_hostname $MYSQL_HOST  --db_username $MYSQL_USERNAME --db_password "" --db_database $DATABASE  --username admin --password admin --email admin@example.com --agree_tnc yes --http_server $DOMAIN 
